[package]
name = "event_notifier_serenity"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = {version = "0.12", features = ["full"] }
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
dotenv = "0.15"
lazy_static = "1.5.0"